apiVersion: batch/v1
kind: Job
metadata:
  name: emptyboxes-endpoint-importer-job
  labels:
    app.kubernetes.io/name: endpoint-importer
    app.kubernetes.io/instance: emptyboxes-mapper-endpoint-importer-1
    app.kubernetes.io/version: '0.1'
    app.kubernetes.io/component: endpoint-importer
    package: emptyboxes
spec:
  backoffLimit: 3
  template:
    spec:
      initContainers:
        - name: emptyboxes-check-mapper-status
          image: busybox:1.28
          command: ['sh', '-c', 'until telnet mapper-service 3003; do echo Mapping mediator not running yet; sleep 10; done;']
      containers:
        - name: emptyboxes-endpoint-importer
          image: jembi/instantohie-config-importer
          args:
            - sh
            - -c
            - wait-on -t 60000 http-get://emptyboxes-mapper-service:3003/uptime && node endpoint.js
          env:
            - name: MEDIATOR_HOST_NAME
              value: 'emptyboxes-mapper-service'
            - name: MEDIATOR_API_PORT
              value: '3003'
          volumeMounts:
            - mountPath: /importer
              name: emptyboxes-endpoint-importer
      restartPolicy: OnFailure
      volumes:
        - name: emptyboxes-endpoint-importer
          configMap:
            name: emptyboxes-endpoint-importer-configmap
