apiVersion: batch/v1
kind: Job
metadata:
  name: covid19-immunization-opencr-config-importer-job
  labels:
    app.kubernetes.io/name: opencr-config-importer
    app.kubernetes.io/instance: covid19-immunization-opencr-config-importer-1
    app.kubernetes.io/version: '0.1'
    app.kubernetes.io/component: config-importer
    package: covid19immunization
spec:
  backoffLimit: 3
  template:
    spec:
      initContainers:
        - name: covid19immunization-check-opencr-status
          image: busybox:1.28
          command: ['sh', '-c', 'until telnet opencr 3004; do echo OpenCR not running yet; sleep 10; done;']
      containers:
        - name: covid19-immunization-opencr-config-importer
          image: jembi/instantohie-config-importer
          args:
            - sh
            - -c
            - wait-on -t 60000 http-get://opencr:3004/crux && node opencrConfig.js
          env:
            - name: OPENCR_HOST_NAME
              value: opencr
            - name: OPENCR_API_PORT
              value: '3004'
          volumeMounts:
            - mountPath: /importer
              name: covid19-immunization-opencr-config-importer-config
      restartPolicy: OnFailure
      volumes:
        - name: covid19-immunization-opencr-config-importer-config
          configMap:
            name: covid19-immunization-opencr-config-importer-configmap
