configMapGenerator:
  - name: covid19-immunization-hapi-fhir-config-importer-configmap
    files:
      - ./volume/fhirConfig.js
      - ../../package.json
resources:
  - ./exmptyboxes-hapi-fhir-config-importer-job.yaml