configMapGenerator:
  - name: covid19-immunization-endpoint-importer-configmap
    files:
      - ./volume/endpoint.js
  - name: covid19-immunization-hapi-fhir-config-importer-configmap
    files:
      - ./volume/fhirConfig.js
  - name: covid19-immunization-mapper-config-importer-configmap
    files:
      - ./volume/openhimConfig.js
resources:
  - ./emptyboxes-hapi-fhir-config-importer-job.yaml
  - ./emptyboxes-endpoint-importer-job.yaml
  - ./emptyboxes-mapper-config-importer-job.yaml