apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptyboxes-mapper-deployment
  labels:
    package: emptyboxes
spec:
  replicas: 1
  selector:
    matchLabels:
      component: emptyboxes-mapper
  template:
    metadata:
      labels:
        component: emptyboxes-mapper
    spec:
      initContainers:
        - name: emptyboxes-check-openhim-status
          image: busybox:1.28
          command: ['sh', '-c', 'until telnet openhim-core-service 8082; do echo OpenHIM not running yet; sleep 10; done;']
      containers:
        - name: emptyboxes-mapper
          image: jembi/openhim-mediator-mapping:v2.2.2
          ports:
            - containerPort: 3003
          env:
            - name: OPENHIM_URL
              value: https://openhim-core-service:8082
            - name: OPENHIM_USERNAME
              value: root@openhim.org
            - name: OPENHIM_PASSWORD
              value: instant101
            - name: MONGO_URL
              value: mongodb://mongo-0.mongo-service,mongo-1.mongo-service,mongo-2.mongo-service/emptyboxes-mediator?replicaSet=mongo-set
            - name: PARSER_LIMIT
              value: 10mb
          resources:
            limits:
              memory: "2Gi"
              cpu: "3"
            requests:
              memory: "512Mi"
              cpu: "1"
